projects:
  app:
    schemaPath: ${env:GRAPHQL_SCHEMA}
    extensions:
      endpoints:
        default: ${env:APP_DEFAULT_ENDPOINT}
  prisma:
    schemaPath: ${env:PRISMA_GENERATED}
    extensions:
      prisma: prisma.yml
